config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  resources :reviews, only: [:index, :new, :create, :destroy]
  
  resources :products, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  
  mount_uploader :image_user, ImageUploader
  
  validates :name, presence: true, length: { maximum: 50 }
  enum sex: { male: 1, female: 2 }
  validates :age, numericality: { greater_than_or_equal_to: 18 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @reviews = Review.all.page(params[:page])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:success] = '口コミを投稿しました。'
      redirect_to root_url
    else
      @reviews = current_user.reviews.order('created_at DESC').page(params[:page])
      flash.now[:danger] = '口コミの投稿に失敗しました。'
      redirect_to root_url
    end
  end

  def destroy
    @review.destroy
    flash[:success] = '口コミを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def review_params
    params.require(:review).permit(:product_id, :point, :content)
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order('created_at DESC').page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

    

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
 
    #編集しようとしてるユーザーがログインユーザーとイコールかをチェック
  if current_user == @user
    
    if params[:image_user]
      @user.image = "#{@user.id}.jpg"
      image = params[:image_user]
      File.binwrite("user_images/#{@user.image}", image.read)
      flash[:success] = '画像を保存しました。'
    end
 
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を編集しました。'
      render :edit
    else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
      render :edit
    end   
 
  else
    redirect_to root_url
  end
   
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :image_user, :age, :sex)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">FriendMatch</a>
      </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ユーザー一覧', users_path %></li>
            <li><%= link_to '育毛剤一覧', products_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'My profile', user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Microposts</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_products.html.erb
<% if products.any? %>
  <ul class="media-list">
    <% products.each do |product| %>
      <li class="media">
        <div class="media-left">
          <% if product.image.present? %>
            <%= image_tag product.image.url %>
          <% else %>
            <div class="product">
              <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
            </div>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= product.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', product_path(product) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate products %>
<% end %>

app/views/products/index.html.erb
<%= render 'products', products: @products %>

app/views/products/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @product.name %></h3>
      </div>
      <div class="panel-body">
         <% if @product.image.present? %>
           <%= image_tag @product.image.url %>
          <% else %>
            <div class="user">
              <%=  image_tag("/user_images/wanko.jpg", :size => "400×400") %>
            </div>
          <% end %>
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li><a href="#">Microposts</a></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
  </div>
</div>

app/views/reviews/_reviews.html.erb
<% if reviews.any? %>
  <div class="reviews-index-item">
  <ul class="media-list">
    <% reviews.each do |review| %>
      <li class="media">
        <div class="media-left">
          <% if review.user.image_user.present? %>
            <%= image_tag review.user.image_user.thumb.url %>
          <% else %>
            <div class="user">
              <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
            </div>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <p>投稿者: <%= review.user.name %></p>
          </div>
          <div>
            <p>
              <p>商品名: <%= review.product.name %></p>
            </p>
            
            <p>評価：<div class="star-rating" data-score= <%= review.point %>></div></p>
           
            <p>
              感想：<%= review.content %>
            </p>
            <p>
              <%= link_to 'View profile', review_path(review) %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate reviews %>
<% end %>

  
<script>
$('.star-rating').raty({
  path: '/assets',
  readOnly: true,
  score: function() {
  return $(this).attr('data-score');
  
  }
});
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/index.html.erb
<%= render 'reviews', reviews: @reviews %>

app/views/reviews/new.html.erb
<%= javascript_include_tag 'jquery.raty.js' %>
<aside class="col-md-4">
      
  <%= form_for(@review) do |f| %>
  

  <div class="form-group">
    <%= f.label :product_id %>
    <%= f.collection_select :product_id, Product.all, :id, :name,:prompt => "なんか選んでよ" %>
    
    <div id="star">
        <%= f.label :star %>
        <%= f.hidden_field :point, id: :review_point %>
    </div>
    
    <%= f.text_area :content, class: 'form-control', rows: 5 %>
  </div>
        
  <%= f.submit '送信', class: 'btn btn-primary btn-block' %>

<% end %>
</aside>

<h1>Ajax#index</h1>
<p id="hoge">赤色になるよ</p>


<script>
  
$('#star').raty({
  size     : 36,
  starOff:  '<%= asset_path('star-off.png') %>',
  starOn : '<%= asset_path('star-on.png') %>',
  scoreName: 'review[point]' ,
});

</script>

app/views/toppages/index.html.erb
<% if logged_in? %>
  
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Microposts</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

<div class="text-center">
  <h1>Welcome to the Microposts</h1>
  <%= link_to '口コミを投稿する', new_review_path, class: 'btn btn-lg btn-primary' %>
  <%= link_to '口コミを見る', reviews_path, class: 'btn btn-lg btn-primary' %>
</div>

<h1>Ajax#index</h1>
<p id="hoge">赤色になるよ</p>

<script>
  $("#hoge").css("color","red")
</script>

app/views/users/_users.html.erb
<% if users.any? %>

  <ul class="media-list">
    
    <% users.each do |user| %>

      <li class="media">
        <div class="media-left">
          <% if user.image_user.present? %>
            <%= image_tag user.image_user.thumb.url %>
          <% else %>
            <div class="user">
              <%=  image_tag("/user_images/wanko.jpg", :size => "40×40") %>
            </div>
          <% end %>
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p>
              <%= link_to 'View profile', user_path(user) %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

     <%= form_for @user,:url => {:action => 'update'}, :html => {:multipart => true} do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="row">
    <div class="col-xs-6 form-group">
      <%= f.label :age, '年齢', class:'control-label' %>
      <%= f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代以上","70"] ], {},   class: 'form-control' %>
    </div>
 
    <div class="col-xs-6 form-group">
      <%= f.label :sex, '性別', class:'control-label' %>
      <%= f.select :sex, [["",""], ["女性","female"], ["男性","male"]], {},   class: 'form-control' %>
    </div>
    </div>
    
    
    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%=f.label :image_user,"ユーザー画像" %>
      <%= f.file_field :image_user, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :introduce, 'Detail' %>
      <%= f.text_field :introduce, class: 'form-control' %>
    
      <%= f.submit 'プロフィール編集を完了する', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    
<%= form_for(@user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    
    <div class="row">
    <div class="col-xs-6 form-group">
      <%= f.label :age, '年齢', class:'control-label' %>
      <%= f.select :age, [["",""], ["10代","10"], ["20代","20"], ["30代","30"], ["40代","40"], ["50代","50"], ["60代","60"], ["70代以上","70"] ], {},   class: 'form-control' %>
    </div>
 
    <div class="col-xs-6 form-group">
      <%= f.label :sex, '性別', class:'control-label' %>
      <%= f.select :sex, [["",""], ["女性","female"], ["男性","male"]], {},   class: 'form-control' %>
    </div>
    </div>
    
    
    <div class="form-group">
      <%= f.label :password, 'Password' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmation' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%=f.label :image_user,"ユーザー画像" %>
      <%= f.file_field :image_user, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :introduce, 'Detail' %>
      <%= f.text_field :introduce, class: 'form-control' %>
    </div>
    <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
         <% if @user.image_user? %>
           <%= image_tag @user.image_user.url %>
          <% else %>
            <div class="user">
              <%=  image_tag("/user_images/wanko.jpg", :size => "400×400") %>
            </div>
          <% end %>
      </div>
    </div>
  </aside>
  <div class="col-md-8">
  <p class="orange b">名前</p>
  <p><span class="orange b"><%= @user.name %></span>
  <p class="orange b">自己紹介</p>
  <p><%= @user.introduce %></p>
  </div>
  <% if current_user.id == @user.id %>
  <%= link_to 'プロフィールを編集する', edit_user_path(@user) %>
 <% end %>
  
    
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>投稿<span class="badge"><%= @count_posts %></span><% end %></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
    <%= render 'reviews/reviews', reviews: @reviews %>
  </div>
</div>